### ISSUE TITLE
DrRacket Debug Step click requires leaving and re-entering bar to act on subsequent click

### ISSUE THREAD

**Issue by maueroats** [racket/drracket#472] opened 2021-03-16 00:22 UTC
## Version 

Racket 8.0 [cs]

Platform: observed on Linux, Mac OS.

## Steps to reproduce

1. Begin with a program with at least two steps.
```racket
#lang racket
(+ 1 2)
```

2. Hit the "Debug" button.
3. Click step with the mouse.
4. Without leaving the bar that contains the debug button, click it more times. Notice that subsequent clicks have no effect.
5. Leave the bar and re-enter (this step works even if you perform no mouse activity other than motion)
6. Click on the step button. Notice that it responds.

Side note: the button is not on a darker gray background ("lit up"?) when it is not responding to clicks. The background gets a darker gray when you leave the bar and hover over it again.

The program above takes me 4 clicks to complete.

## Expected Behavior

Every click on the Step button advances one step.

**Comment by sorawee** [comment] 2021-03-16 00:26
This is a duplicate of #470. It will be fixed in Racket 8.1. If you can't wait, you can also download a snapshot version (http://snapshot.racket-lang.org/) now.

**Closed by sorawee** 2021-03-16 00:26 UTC

**Comment by maueroats** [comment] 2021-03-16 00:34
TIL, have to check _closed_ issues as well as open ones.
