### ISSUE TITLE
v8.13.0.1: Preferences -> Editing displays very strangely on OSX 14.4.1

### ISSUE THREAD

**Issue by tonyg** [racket/drracket#670] opened 2024-04-24 08:01 UTC
Here's what I see:

![Screenshot 2024-04-24 at 09 57 28](https://github.com/racket/drracket/assets/17710/f2bd0ffd-e41f-4cff-ba85-fc28b93aff6a)

To reproduce:

 - build DrRacket from git
 - open it (with a fresh/empty/default config - this was the first time I ran it on this machine)
 - Command-comma to open settings
 - Click the "Editing" tab.

The version from the "about" window is `8.13.0.1-2024-04-24-fc4b6277b8`, since I built from git.

**Comment by tonyg** [comment] 2024-04-24 08:03
A similar kind of thing happens in other panels of the settings dialog too:

![Screenshot 2024-04-24 at 10 03 04](https://github.com/racket/drracket/assets/17710/2c7409aa-0080-4342-9f4b-eca8473cd92e)

**Comment by sorawee** [comment] 2024-04-24 08:21
So I'm not the only one!!!

**Comment by sorawee** [comment] 2024-04-24 08:24
Technically a duplicate of #652

**Comment by tonyg** [comment] 2024-04-24 09:32
Tab-stops are very large too. Is there something off about font-metrics?

**Comment by sorawee** [comment] 2024-04-25 23:56
Fixed by https://github.com/racket/gui/pull/326

**Closed by sorawee** 2024-04-25 23:56 UTC
