### ISSUE TITLE
Debugger in ASL doesn't (always) show PITCH

### ISSUE THREAD

**Issue by rfindler** [racket/drracket#19] opened 2015-11-04 16:11 UTC
This program, in the language-dialog version of ASL, shows too many frames when you repeatedly click "step" in the debugger (the calls to "f" stack up in the "stack" pane of the debugger):

```
(define (f x) (if (zero? x) x (f x)))
(f 1)
```

This program, in contrast:

```
(define (f x) (f x))
(f 1)
```

does not have that problem.

**Comment by florence** [comment] 2015-11-04 16:20
This problem can be reproduced in full racket:

1. Turn on "Syntactic Test Suite Coverage"
2. Use the program:

```
#lang racket

(define (loop)
  (begin0 ;; <- for some reason ASL sometimes inserts these
    (loop)))

(loop)
```

3. Start the debugger, and step through. Watch the stack grow!

**Comment by florence** [comment] 2015-11-04 16:50
I should note: If you don't use the debugger and just run the program tail calls happen property (evidence: the program never runs out of memory). So it seems this has something to do with how the test coverage (errortrace), the debugger, and `begin0` interact.

**Comment by greghendershott** [comment] 2015-11-04 16:55
Although I barely understand this code, maybe this is because `begin0` needs similar `is-tail?` treatment as `begin`? (Although I guess for the first body not the last?)

https://github.com/racket/drracket/blob/master/drracket/gui-debugger/annotator.rkt#L345-L357

```
            [(begin . bodies)
             (letrec ([traverse
                       (lambda (lst)
                         (if (and (pair? lst) (equal? '() (cdr lst)))
                             `(,(annotate (car lst) bound-vars is-tail? module-name ))
                             (cons (annotate (car lst) bound-vars #f module-name )
                                   (traverse (cdr lst)))))])
               (quasisyntax/loc expr (begin #,@(traverse (syntax->list #'bodies)))))]
            
            [(begin0 . bodies)
             (quasisyntax/loc expr (begin0 #,@(map (lambda (expr)
                                                     (annotate expr bound-vars #f module-name ))
                                                   (syntax->list #'bodies))))]
```

**Comment by rfindler** [comment] 2015-11-04 16:56
It appears to only be the debugger's annotation. Turning off errortrace in the language dialog and then clicking "debug" and "go" gives the wrong printouts for this program (showing growth):

```
#lang racket
(define (f x)
  (cond
    [(zero? x) x]
    [else
     (with-continuation-mark 'x x
       (begin0
        (begin
          (printf "~s\n" (continuation-mark-set->list
(current-continuation-marks) 'x))
          (f (- x 1)))))]))
(f 10)
```

**Comment by samth** [comment] 2015-11-04 16:57
@greghendershott I think it needs that annotation precisely when there's only one expression in the `begin0`.

**Comment by rfindler** [comment] 2015-11-04 17:58
@greghendershott nice catch, thanks!

**Comment by greghendershott** [comment] 2015-11-04 18:28
You're welcome but @florence is the one who narrowed it down to `begin0`.

I knew where to look next, only from having used the debugger annotation code a few months ago in a (experimental, not merged to master) branch of racket-mode.

**Closed** 2015-11-09 12:38 UTC
