### ISSUE TITLE
Tab Manuevering

### ISSUE THREAD

**Issue by cschnelz** [racket/drracket#356] opened 2020-03-13 16:38 UTC
DrRacket 7.6.
It would be nice if dragging on the top of the tab window could be used to reorganize the positions of open tabs.  ie switch something you recently opened to be on the furthest left rather than the furthest right.

**Comment by rfindler** [comment] 2021-01-02 01:08
This is a duplicate of https://github.com/racket/drracket/issues/124 (and there has been some progress recently).

**Closed by rfindler** 2021-01-02 01:08 UTC
