### ISSUE TITLE
missing macro stepper, debug buttons

### ISSUE THREAD

**Issue by willghatch** [racket/drracket#57] opened 2016-05-23 20:28 UTC
The row of buttons at the top is missing Debug, Check Syntax, and Macro stepper (though it still has Run and Stop).  I'm using Racket version 6.5 on Arch Linux.

Steps to reproduce:

`echo -e '#lang racket/base\n"hello"' > foo.rkt`
`drracket foo.rkt`

and the buttons are missing.  Then:

`rm ~/.racket/racket-prefs.rktd`
`drracket foo.rkt`

and the buttons are _usually_ back.  Then:

`drracket foo.rkt`

and the buttons are gone again (seemingly because racket-prefs.rktd is back).

**Comment by rfindler** [comment] 2016-05-24 14:40
I don't see this on my machine, and my guess is that it probably has something to do with the timing of callbacks.

What happens if you change the "#lang" line at the top of the window from "#lang racket" to "#lang racke" (delete the "t") and back? And if that doesn't bring them back, what if you change it to "#lang scribble/base" and back? Do you see new scribble buttons when you do that?

**Comment by willghatch** [comment] 2016-05-24 20:54
>What happens if you change the "#lang" line at the top of the window from "#lang racket" to "#lang racke" (delete the "t") and back? And if that doesn't bring them back, what if you change it to "#lang scribble/base" and back? Do you see new scribble buttons when you do that?

If I have more buttons than just Run and Stop and I change the #lang
line, I lose all of them but Run and Stop, and they never come back if I
change it to `#lang racket` or `#lang scribble/base`.  If I start it up with no
racket-prefs.rktd on a file with `#lang scribble/base` I get Debug,
Check Syntax, Macro Stepper, and then a blank space that looks like it
should have a button, then Run and Stop.  Sometimes when I open drracket
on a file with `#lang racket/base` (and no racket-prefs.rktd), then the
Macro Stepper button is missing but there is a space left where it
should be.  Yesterday the Macro Stepper button was *usually* there, but
today it usually isn't.

**Comment by takikawa** [comment] 2016-07-20 03:17
I've been experiencing this problem too and asked on IRC if anyone else had the same issue. So far I've noticed that I can reproduce it on my work machine that has GTK 3.20 but not on my laptop with GTK 3.14. Someone else on Fedora and GTK 3.20 also reported seeing the issue. So maybe it could be a compatibility issue with newer GTKs? (release notes on GTK compat here: https://git.gnome.org/browse/gtk+/plain/README.in?id=3.20)

Also I've noticed some workarounds include: setting GTK2 via an environment variable and toggling the toolbar orientation.

**Comment by takikawa** [comment] 2016-07-22 21:15
Here is a more minimal example that I think illustrates the issue:

```
#lang racket/gui

(require mrlib/switchable-button)

(define f (new frame% [label "foo"]))

(define (do-button x)
  (send f begin-container-sequence)
  (define bm (make-bitmap 50 50))
  (define dc (new bitmap-dc% [bitmap bm]))
  (send dc draw-rectangle 0 0 30 30)
  (new switchable-button%
       [parent f]
       [label (~a "Button " x)]
       [bitmap bm]
       [callback (lambda (sb) (void))]
       [min-width-includes-label? #t])
  (send f end-container-sequence))

(do-button 1)
(do-button 2)
(do-button 3)

(send f show #t)
```

Running this with GTK3 shows no buttons. In GTK2 it shows buttons. Removing the container sequence function calls makes it show the buttons again---these calls mimic what DrRacket does for tool-added buttons.

**Comment by mflatt** [comment] 2016-08-21 14:17
Thanks for the smaller example! The relevant feature of switchable buttons turns out to be that they're non-stretchable.
racket/gui@6b2f4a72aebbd689add17b3fc3bc48a4cf287fa5 is intended to fix the bug.

**Comment by willghatch** [comment] 2016-08-30 18:49
That fixed it for me.  This can be closed as far as I'm concerned.

**Comment by skorokithakis** [comment] 2017-04-12 12:08
I get this with 6.6 in Ubuntu 16.10. Are there any workarounds for the months until the next version?

**Comment by jbclements** [comment] 2018-03-06 17:04
@skorokithakis is this still an issue for you? I'm closing this because it appears to have been resolved.

**Closed by jbclements** 2018-03-06 17:04 UTC

**Comment by skorokithakis** [comment] 2018-03-06 17:06
I'm afraid I don't use Dr Racket any more, so yes :)
