### ISSUE TITLE
Error when launching DrRacket

### ISSUE THREAD

**Issue by Reilithion** [racket/drracket#648] opened 2023-10-30 22:55 UTC
When launching DrRacket, I get the following error:

> match: no matching clause for '#(syncheck:add-definition-target 27479 27499 contract-defs-submod (#%contract-defs-reference))
  location...:
   share\pkgs\drracket\drracket\private\syncheck\gui.rkt:2250:10
  context...:
   C:\Program Files\Racket\share\pkgs\drracket\drracket\private\syncheck\gui.rkt:2209:10: loop
   C:\Program Files\Racket\share\pkgs\drracket\drracket\private\module-language.rkt:2356:2: oc-monitor-value
   C:\Program Files\Racket\share\pkgs\gui-lib\mred\private\wx\common\queue.rkt:436:6
   C:\Program Files\Racket\share\pkgs\gui-lib\mred\private\wx\common\queue.rkt:487:32
   C:\Program Files\Racket\share\pkgs\gui-lib\mred\private\wx\common\queue.rkt:639:3

The #lang line is:
`#lang typed/racket/base`

I have run `raco setup` with admin privileges as well as `racket -y`. The behavior has not changed after doing so.

**Comment by rfindler** [comment] 2023-10-30 23:10
Can you supply a complete file that causes this issue (we'd need a program that expands successfully to reproduce I believe)?

**Comment by Reilithion** [comment] 2023-10-30 23:14
A complete file follows:

```
#lang typed/racket/base
```

In other words, a default, basically empty document causes the issue for me.

**Comment by rfindler** [comment] 2023-10-30 23:15
Which version of DrRacket are you using?

**Comment by Reilithion** [comment] 2023-10-30 23:16
> Welcome to DrRacket, version 8.10, english by PLT.

**Comment by Reilithion** [comment] 2023-10-30 23:18
![drracketerr](https://github.com/racket/drracket/assets/38637/772fd082-ea1b-4a40-868f-aaae769dd4f9)

**Comment by rfindler** [comment] 2023-10-30 23:20
Hm. I'm not able to see why that would happen from code inspection nor can I make it happen in my installation. 

It is a problem for online expansion so you can probably make it go away by right clicking on the small circle at the bottom right of the window and selecting "Disable Background Expansion". Sorry I don't have anything more useful to offer.

**Comment by Metaxal** [comment] 2023-10-31 06:58
Perhaps try to delete or rename the prefs.rktd file?

**Comment by Reilithion** [comment] 2023-10-31 20:25
> Perhaps try to delete or rename the prefs.rktd file?

I tried this and it did not resolve the issue. I checked to make sure I get the same error, and it appears to be exactly the same.

**Comment by rfindler** [comment] 2023-12-29 22:12
I'm going to close this because I cannot reproduce it. From my memory and looking at the error message, it looks like two parts of DrRacket are out of sync with each other (as if one file is from one version of DrRacket and another is from another).

Please feel free to reopen if there is new information that could help us track down what actually went wrong.

**Closed by rfindler** 2023-12-29 22:12 UTC
