### ISSUE TITLE
File > Open Recent sometimes not populated

### ISSUE THREAD

**Issue by LiberalArtist** [racket/drracket#223] opened 2018-07-23 00:24 UTC
With DrRacket 6.90.0.901 on Mac OS 10.13.5, if I open a file using the `File` > `Open Recent` menu, then immediately try to open another file using `File` > `Open Recent`, the `Open Recent` item doesn't open up a submenu to choose from. If I switch back to the previous DrRacket window, `Open Recent` seems to work again. 

The problem may happen under a broader set of conditions, but I seem to be able to reproduce it consistently this way. I can try it in 6.12 later, but I don't remember this being a problem before.

**Comment by rfindler** [comment] 2018-07-23 00:37
As best I understand it, this bug is caused by a limitation of the underlying windowing toolkit; if an `on-demand` callback takes too long then it is aborted and populating that menu can sometimes take too long. I've tried various ways to hack around this limitation by doing most of the computation outside of that context, but I can't quite seem to get it consistently fast enough.

Another set of eyes would be most welcome, tho.

**Comment by DexterLagan** [comment] 2020-05-01 13:27
DrRacket 7.6 exhibits the same problem on my system (Windows 10 64).

**Comment by mflatt** [comment] 2020-05-01 13:32
The problem on Windows for v7.6 should be fixed for the upcoming v7.7 release: racket/gui#168

**Comment by DexterLagan** [comment] 2020-05-01 13:52
Thanks! I'd like to tackle that delay after startup (GC?) as well as the
relatively slow scrolling. Any pointers as to where I should look?
Also, I've been getting a small problem since 7.6: I'd be editing code and
entering a comment, when all of the code above the line gets highlighted as
comment (all the way up to the beginning of the file). Pressing F6 updates
the highlighting but leaves pieces of code as comment. Running the program
often fixes the problem. I'll try to find what exactly I'm doing to make
this happen and post an issue.

Have a good weekend,

Dex

**Comment by spdegabrielle** [comment] 2021-11-26 22:00
Is this fixed?

I'm getting a similar but possibly unrelated issue #532

**Comment by spdegabrielle** [comment] 2021-11-26 22:01
The behaviour described in this ticket is not happening for me. Closing.

**Closed by spdegabrielle** 2021-11-26 22:01 UTC
