### ISSUE TITLE
DrRacket Internal Error with blue boxes

### ISSUE THREAD

**Issue by AlexKnauth** [racket/drracket#9] opened 2015-06-27 00:54 UTC
I required `srfi/1`, typed `append-reverse`, and now I'm getting this, and also every time I try to close the DrRacket Internal Error window, another one pops up.
```
cdr: contract violation
  expected: pair?
  given: '()
  context...:
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/share/pkgs/drracket/drracket/private/syncheck/blueboxes-gui.rkt:928:0: get-blue-box-size
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/share/pkgs/drracket/drracket/private/syncheck/blueboxes-gui.rkt:318:4: get-box-upper-right-and-lock-coordinates method in ...ck/blueboxes-gui.rkt:173:2
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/share/pkgs/drracket/drracket/private/syncheck/blueboxes-gui.rkt:546:4: in-blue-box? method in ...ck/blueboxes-gui.rkt:173:2
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/share/pkgs/drracket/drracket/private/syncheck/blueboxes-gui.rkt:353:4: adjust-cursor method in ...ck/blueboxes-gui.rkt:173:2
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/share/pkgs/gui-lib/mred/private/wxme/editor-canvas.rkt:394:2: on-event method in editor-canvas%
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/collects/racket/private/more-scheme.rkt:147:2: call-with-break-parameterization
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/collects/racket/private/more-scheme.rkt:264:2: call-with-exception-handler
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/share/pkgs/gui-lib/mred/private/wx/cocoa/window.rkt:800:4: dispatch-on-event method in window%
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:454:6
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:505:32
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:653:3
```

**Comment by AlexKnauth** [comment] 2015-06-27 00:56
Also after trying some other things, I got this error box after (I think) hitting the up arrow key:
```
sequence-contract-violation: negative: method move-position cannot be called, except in states (unlocked write-lock), args 'up
  context...:
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/share/pkgs/gui-lib/mred/private/wxme/text.rkt:5894:21: send-arg7654
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/share/pkgs/gui-lib/mred/private/wxme/keymap.rkt:736:2: core989
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/share/pkgs/gui-lib/mred/private/wxme/keymap.rkt:508:2: chain-handle-key-event method in keymap%
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/share/pkgs/gui-lib/mred/private/wxme/keymap.rkt:508:2: chain-handle-key-event method in keymap%
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/share/pkgs/gui-lib/mred/private/wxme/keymap.rkt:496:4: for-loop
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/share/pkgs/gui-lib/mred/private/wxme/keymap.rkt:508:2: chain-handle-key-event method in keymap%
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/share/pkgs/gui-lib/mred/private/wxme/keymap.rkt:459:2: handle-key-event method in keymap%
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/share/pkgs/gui-lib/mred/private/wxme/editor.rkt:214:2: on-local-char method in editor%
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/share/pkgs/gui-lib/mred/private/wxme/editor-canvas.rkt:455:2: on-char method in editor-canvas%
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/collects/racket/private/more-scheme.rkt:147:2: call-with-break-parameterization
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/collects/racket/private/more-scheme.rkt:264:2: call-with-exception-handler
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/share/pkgs/gui-lib/mred/private/wx/cocoa/window.rkt:790:4: dispatch-on-char method in window%
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:454:6
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:505:32
   /Applications/Racket/2015-06-08/Racket v6.2.0.4/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:653:3
```

**Comment by rfindler** [comment] 2015-06-27 01:02
The second one looks like a symptom of something being left in a bad state.

**Comment by AlexKnauth** [comment] 2015-06-27 01:06
Restarting didn't help. I restarted, clicked on the append-reverse identifier, and got the same error, and then DrRacket seemed to freeze.

**Comment by rfindler** [comment] 2015-06-27 01:09
This one reproduced for me, so I've pushed a fix (and hit the "update" button on pkgs.racket-lang.org)

This is the commit: https://github.com/racket/drracket/commit/8e5ea4e6f44565325a73d09e546d1681ee1d28ce

**Closed by rfindler** 2015-06-27 01:09 UTC

**Comment by AlexKnauth** [comment] 2015-06-27 13:20
I'm wondering, would converting `blueboxes-gui.rkt` to typed racket prevent errors like this and https://github.com/racket/drracket/issues/8 for good? Or is there a reason why it hasn't been converted?

**Comment by rfindler** [comment] 2015-06-27 14:02
It probably would, yes. I think #8 is the same issue, but the fix I made was wrong because I was confused about the types (it was a non-empty list of strings and I put some empty lists in).

**Comment by AlexKnauth** [comment] 2015-06-27 18:57
I started trying to convert it, but I got a bunch of errors like this:
```
. Type Checker: missing type for identifier;
 consider using `require/typed' to import it
  identifier: generate-local-member-name
  from module: racket/private/class-internal in: #%module-begin
```

**Comment by AlexKnauth** [comment] 2015-06-27 18:58
And also this:
```
. Type Checker: missing type for identifier;
 consider using `require/typed' to import it
  identifier: compose-interface
  from module: racket/private/class-internal in: (interface () get-docs-im get/start-docs-im get-require-candidates get-path->pkg-cache update-the-strs toggle-syncheck-docs)
. Type Checker: missing type for identifier;
 consider using `require/typed' to import it
  identifier: validate-local-member
  from module: racket/private/class-internal in: (interface () get-docs-im get/start-docs-im get-require-candidates get-path->pkg-cache update-the-strs toggle-syncheck-docs)
```

**Comment by rfindler** [comment] 2015-06-27 19:05
Looks like something in the class system that that file uses isn't
supported.

Not a very clear error message, tho.

@samth ?

**Comment by AlexKnauth** [comment] 2015-06-27 19:15
Also `color:text<%>` seems to be missing from `typed/framework`

**Comment by AlexKnauth** [comment] 2015-06-27 19:26
Oh, right, I forgot interfaces weren't supported.

**Comment by samth** [comment] 2015-06-28 14:59
@takikawa will know better about typed class support.
