### ISSUE TITLE
Stepper does not always choose fresh identifiers when evaluating local expressions

### ISSUE THREAD

**Issue by pnijjar** [racket/drracket#250] opened 2018-12-09 23:32 UTC
One of our students discovered the following problem with the stepper. This is using the "Intermediate Student with Lambda" teaching language. 

```
(define x_0 3)
(local [(define x 2)] x)
```

The stepping rules for `local` say that the identifer `x` should be lifted to the top level and given a fresh, unused name. But if you run this through the stepper you see that the `x` in the `local` gets the name `x_0`, which is already taken. It seems to me that this is a bug in the stepper.

**Comment by jbclements** [comment] 2018-12-09 23:42
Yes, I agree that this is a bug. If it makes you feel any better, it's a *display* bug... you'll see that the stepper still produces the right value; it should just pick a different name for displaying the lifted name. This is a duplicate of an existing bug, but maybe I should fix it rather than talking about it :)

**Comment by pnijjar** [comment] 2018-12-09 23:52
Oops. Sorry. I looked through the bug list to see whether this had been reported, but I obviously missed this. Feel free to close or merge this issue as you see fit. What is the other issue number?

**Comment by jbclements** [comment] 2018-12-10 00:00
Yeah, um... 

https://bugs.racket-lang.org/query/?cmd=view%20audit-trail&database=default&pr=8987&return_url=https%3A%2F%2Fbugs.racket-lang.org%2Fquery%2F%3Fdatabase%3Ddefault%3Bdebug%3D%3Bcmd%3Dsubmit%2520query%3BCategory%3Dstepper%3BClass%3Dany%3BResponsible%3Dany%3BSeverity%3Dany%3BPriority%3Dany%3BState%3Dany%3Bignoreclosed%3DIgnore%2520Closed%3BConfidential%3Dany%3BSubmitter-Id%3Dany%3BSynopsis%3D%3Bmultitext%3D%3Bcolumns%3DCategory%3Bcolumns%3DSynopsis%3Bcolumns%3DClass%3Bcolumns%3DResponsible%3Bcolumns%3DState%3Bcolumns%3DArrival-Date%3Bcolumns%3DLast-Modified%3Bcolumns%3DRelease%3Bsortby%3DNumber%3Bdisplaydate%3DCurrent%2520Date

**Comment by jbclements** [comment] 2018-12-11 00:59
Okay, I have a pull request (on the htdp repo, 

https://github.com/racket/htdp/pull/72

)... that should fix this issue. I'll wait to see if @stchang has a few minutes to review it before merging.

Many thanks for reporting this!

**Comment by jbclements** [comment] 2018-12-12 22:58
okay, I'm closing this now.

**Closed by jbclements** 2018-12-12 22:58 UTC
Labels: bug, stepper
